### PR TITLE
Support for Configurable Products

### PR DESCRIPTION
**Pull request by leek**
This adds support for Configurable products. Currently, it just selects the first values for each attribute. Ideally, you could specify the value for each attribute but that was more than I needed.

### CODE REVIEW

**Comment by witrin** [comment]
Thank you very much for your contribution! Please be patient, I'm hopefully able to review your code in one or two weeks.

**Comment by witrin** [comment]
Please excuse my late response. Would it be possible for you to split the last commit `Adding support for Configurable products` into two commits? One for the re-factoring and one for the feature itself? The reason is, that I'm not sure about the feature for configurable products in it's current state in contrast to the re-factoring you made. It would also be very nice if you could keep the indent of blank lines.

**Comment by leek** [comment]
Sorry @witrin, the blank lines removal is done automatically by my editor based on the established Magento/PHP coding standards. I do not have any available time to tweak commits and since this code has worked in production in its current state since 12/5 I cannot justify spending extra time unless a bug is found.

**Comment by witrin** [comment]
No problem, so I'll do it. AFAIK the Coding Standards of Magento doesn't make any statement about the indentation of empty lines respectively the code sniffer doesn't display any errors on empty lines with correct indentation and it's just more comfortable. This is why I configured my IDE this way.

**Comment by leek** [comment]
Excellent job cleaning up this PR. Thanks! :+1:

**Pull request closed without merging**
